cloudfoundry/docs-cf-admin

enabling-https-to-routers.html.md.erb, index.html.md.erb
[#105148024]
Signed-off-by: Chris Piraino <cpiraino@pivotal.io>
=> Documentation around enabling SSL termination between LB and router

listing-feature-flags.html.md.erb
Includes diego_docker, set_roles_by_username, unset_roles_by_username feature flags.
Also updated with cf CLI commands and minimum CC API version required.
Let me know if you have any questions.
=> Update feature flags documentation #110641336

listing-feature-flags.html.md.erb
Hi there,
Please don't merge this until Dieu has accepted [our story](https://www.pivotaltracker.com/story/show/111601398).
Thanks!
simonleung8 && utako, CF CAPI Team
=> Add task_creation to doc

app-sec-groups.html.md.erb
Also documented several CLI commands that were missing
Docs team, can we get this on staging site for review?
=> Adding additional public networks example

app-sec-groups.html.md.erb
* add Typical Application Security Groups section
* fix technical errors
* add a bunch of Notes
=> Update Application Security Groups page

app-sec-groups.html.md.erb
This is for CF CLI 6.20.0+.
Github UI added a new line at the end of the file.
=> Binding ASG's can be set on all spaces in org

_migrate_enable_oss.html.md.erb, _migrate_final_redeploy_oss.html.md.erb, _migrate_scale_oss.html.md.erb, app-sec-groups.html.md.erb, apps-enable-diego.html.md.erb, buildpacks.html.md.erb, enabling_ipv6.html.md.erb, notifications.html.md.erb, securing-traffic.html.md.erb, uaa-user-management.html.md.erb
Spaces, it is aligned to view code with any editor, including the web
page view (such as in the GitHub code). When use tabs, the view on the
page is chaos, and it is terrible to mix tabs and spaces.
=> Replace the tab with 4 spaces

_c2c_oss_enable.html.md.erb, container-networking.html.md.erb, index.html.md.erb
cc @jaydunk @rusha19
CF Networking Tracker story here: https://www.pivotaltracker.com/story/show/138951077
=> netman-release renamed to cf-networking-release

docker.html.md.erb
Sorry for the whitespace diffs! We made a couple additions, which include the Docker Volume Support section and an addendum to the Docker Security Concerns in a Multi-Tenant Environment.
[#139759481](https://www.pivotaltracker.com/story/show/139759481)
Signed-off-by: Jeff Pak <jeffrey.pak@emc.com>
=> update docker docs regarding volume services

index.html.md.erb, troubleshooting_tcp_routing.html.md.erb
Hi docs, please find a new Troubleshooting TCP Router page, along with an edited index page. The OSS subnav change will come shortly. Please let us know if we've missed out on anything, thanks!
Thanks!
cc @shalako
=> adds new troubleshooting tcp routing page and index reference

routing-is.html.md.erb
This PR includes changes for isolation segment documentation.
Signed-off-by: Nino Kodabande <ninok@hpe.com>
=> Add documentation for Sharding Routing table

routing-is.html.md.erb
-cc.diego.temporary_local_apps flag must be set to true
[#146390475]
Let us know if you have any questions.
Thanks,
CF Routing
@jberkhahn and @belinda-liu
=> Add cc configration documentation to routing isolation segments page

index.html.md.erb, trusted-system-certificates.html.md.erb
[finishes #145479641]
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>
=> adds documentation for administrators interested in setting up trusted certs

index.html.md.erb, trusted-system-certificates.html.md.erb
=> Edit topic on configuring trusted certs for apps

_ssl_termin_gorouter_lb_oss.html.md.erb, _ssl_termin_gorouter_oss.html.md.erb, securing-traffic.html.md.erb
Hi,
This PR includes updating docs for the following features
- Replace router.ssl_cert and router.ssl_key with router.tls_pem property.
- Support for SNI
Pivotal tracker story: https://www.pivotaltracker.com/story/show/105894964
Regards
Shash
CF Routing
=> Update docs with new routing features 

bbs-encryption-keys.html.md.erb, index.html.md.erb
=> Add BBS data store encryption to index

routing-is.html.md.erb
adding missing ports to the Step 6 section
Missing ports were `4103,8082,8891` from `is1-to-shared`
=> adding missing ports to the Step 6 section

enabling_ipv6.html.md.erb
IPv6 is supported now for EC2 instances
=> update on aws

enabling_ipv6.html.md.erb
Reverts cloudfoundry/docs-cf-admin#114
=> Revert "update on aws"

index.html.md.erb, instance-identity.html.md.erb
[#154001854]
Signed-off-by: Charlie Vieth <cviethjr@pivotal.io>
=> Document Diego Instance Identity

encrypting-cc-db.html.md.erb, index.html.md.erb
[#158734896]
Signed-off-by: Mike Kenyon <mkenyon@pivotal.io>
**NOTE** Don't merge until our PM @zrob approves.
=> Add documentation for CC database encryption and key rotation

index.html.md.erb, troubleshooting-router-error-responses.html.md.erb
DON'T MERGE until the PMS have approved.
[#159020527]
Thanks,
@nhsieh, CF Routing Team
=> Add Troubleshooting Router Error Responses page

troubleshooting-router-error-responses.html.md.erb
Co-authored-by: Kauana dos Santos <kdossantos@pivotal.io>
[#159020527]
=> Clarify Troubleshooting Router Error Responses

diego-cell-upgrade.html.md.erb
Relates to https://github.com/cloudfoundry/docs-cf-admin/issues/126
=> Refine current starts wording

max-container-starts.html.md.erb
As a refinement of https://github.com/cloudfoundry/docs-cf-admin/issues/126 following @emalm 's suggestion at https://github.com/cloudfoundry/docs-cf-admin/issues/126#issuecomment-411096759
=> Refine started vs starting wording

encrypting-cc-db.html.md.erb
Please do not merge until @zrob gives the go-ahead, thanks!
[#160563628]
Signed-off-by: Eli Wrenn <ewrenn@pivotal.io>
=> Document that cc encryption label/value mapping should be maintained

encrypting-cc-db.html.md.erb
Please don't merge until @zrob has given the 👌 - Thanks!
[#160565567]
Signed-off-by: Eli Wrenn <ewrenn@pivotal.io>
=> Document CC database encryption validation and how to skip it

encrypting-cc-db.html.md.erb
Hello from CAPI!
Other teams mentioned that 
using indices in our example docs were confusing 
and did not convey how this feature was supposed to be used.
Please wait until @zrob approves this PR before merging it!
https://www.pivotaltracker.com/story/show/160324204
=> Use dates in suggested key names rather than indices

troubleshooting-router-error-responses.html.md.erb
Please don't merge until our PMs have accepted [this story](https://www.pivotaltracker.com/story/show/157521684).
[#157521684]
Co-authored-by: Utako Ueda <uueda@pivotal.io>
=> remove connectionResetOnRead for gorouter errors

routing-is.html.md.erb
- https://github.com/cloudfoundry/loggregator-agent-release/releases/tag/v3.5
[#163563811]
Signed-off-by: Rowan Jacobs <rojacobs@pivotal.io>
=> Document port for system metric agent

stack-auditor.html.md.erb
New functionality was added to stack auditor 0.0.4. Updated docs accordingly
[#166385241]
Co-authored-by: Dan Thornton <dthornton@pivotal.io>
=> New functionality was added to stack auditor 0.0.4. Updated docs

routing-is.html.md.erb
[#163160647] **[Feature]** Improve scalability of application syslog drain system with new syslog agent architecture
=> Document Loggregator Syslog Binding Cache external port

service-mesh.html.md.erb
Hi again!
Just wanted to add some touchups to the docs to fix some articles and some c2c info. This should be the final PR. Thank you! 
- The CF Networking Program
=> fix articles around service mesh

service-mesh.html.md.erb
This is to add the Windows limitation. 
Sorry @ljarzynski , last one I hope.
- CF Networking Program
=> Add one more limitation regarding c2c service mesh

service-mesh.html.md.erb
=> Update limitations in service mesh

service-mesh.html.md.erb
=> Update service mesh limitations

service-mesh.html.md.erb
since we provide the feature that allows the user to configure the external istio domain so I updated the limitation section
=> Update the limilation

troubleshooting_slow_requests.html.md.erb
* add more experiments to narrow down where latency is originating
[#170161002](https://www.pivotaltracker.com/story/show/170161002)
=> update troubleshooting slow requests

metadata.html.md.erb
Wording fix for Metadata Selector Requirement Reference
=> Wording fix for Metadata

notifications.html.md.erb
Fixing the notification documentation, on UAA target, there was a typo
=> Fixing the notification documentation, on UAA target, there was a typo

routing-is.html.md.erb
Related: [#171112674](https://www.pivotaltracker.com/story/show/171112674)
=> Update tables to include Routing API's mTLS port

quota-plans.html.md.erb
This new link is dependent on this other docs PR we made: https://github.com/cloudfoundry/docs-dev-guide/pull/402
[#172150410](https://www.pivotaltracker.com/story/show/172150410)
cc @christianang
=> Link to new network policy quotas section

routing-is.html.md.erb
Co-authored-by: Gary Liu <galiu@pivotal.io>
Co-authored-by: Mark Stokan <mstokan@pivotal.io>
[#172687096] Gate the Publish to Pivnet job on the Upload to Pivnet job
=> fix some property names

listing-feature-flags.html.md.erb
[#174215923](https://www.pivotaltracker.com/story/show/174215923)
=> Add documentation for `resource_matching` feature flag

metadata.html.md.erb
See related PRs for additional background
https://github.com/cloudfoundry/cloud_controller_ng/pull/2156 
https://github.com/cloudfoundry/cloud_controller_ng/pull/2158
=> Document annotations sent to service brokers

troubleshooting-router-error-responses.html.md.erb
❓ Can you update this in all versions please?
Thanks!
=> update stale route docs

quota-plans.html.md.erb
log_rate_limit is now a part of the quotas. 
Also updated docs with latest output in the examples.
=> Update Quota doc to include Log Rate Limit

troubleshooting-router-error-responses.html.md.erb
Align documentation with gorouter [PR-335](https://github.com/cloudfoundry/gorouter/pull/335)
=> Gorouter maxAttempts configurable for endpoints and route-services

_w3c_oss_config.html.md.erb, w3c_tracing.html.erb
Add page for Enabling W3C tracing
=> Add W3C tracing page

configure-lb-healthcheck.html.md.erb
@anita-flegg , we had some things in this PR that we were unsure about:
* Is there a variable for the IST tile name? 
* We only want this to be in open source docs and and in TAS 6.0+ docs. Did we make this PR to the correct branch?
=> Update lb docs for new loadbalancing configurations

troubleshooting-router-error-responses.html.md.erb
=> Update access log format for new opt-in fields

listing-feature-flags.html.md.erb
Documents the feature flag for enabling CNBs.
=> Document diego_cnb feature flag

distributed-tracing.html.md.erb
See https://github.com/cloudfoundry/cli/issues/3309
=> Add CLI B3 Trace docs

extended-app-support.html.md.erb
- Extended App Support tile documentation
=> Extended App Support tile

docker.html.md.erb
Cloud Controller recently gained some new features for running Docker apps. Note the security implications and try to de-emphasize the difference between Buildpack and Docker apps as security for the two on the platform is more uniform now.
=> Update documentation of docker app security features
