cloudfoundry/docs-cf-admin

- enabling-https-to-routers.html.md.erb
Update docs with information around Subject Alternative Name extension that could be used to deploy a certificate on CF router which includes multiple domains.
Story link: https://www.pivotaltracker.com/story/show/105148024
> Add information multiple domains associated to single certificate

- enabling-https-to-routers.html.md.erb
This PR is to remove the limitation of "X-Forwarded-Proto" not being included in the request from gorouter to apps. If "X-Forwarded-Proto" is not present in the request to gorouter then it will include it in the request to app by using the scheme with which the request was made to gorouter.
Regards,
@atulkc and @ishustava
Pivotal tracker story link: https://www.pivotaltracker.com/story/show/105895048
> Remove X-Forwarded-Proto limitation from docs

- quota-plans.html.md.erb
'quota_definitions' currently shows up at the same level as 'default' and 'silver_quota'
> Fix indentation on documentation

- apps-enable-diego.html.md.erb
The command ``cf diego-apps -o MY-ORG`` outputs
```
Getting apps on the Diego runtime [...]
```
However, the documentation says
```
Getting apps on the DEA runtime [...]
```
> Fix example call output of cf diego-apps

- quota-plans.html.md.erb
Add a note that updates to quotas in manifest are not applied.
This addresses https://github.com/cloudfoundry/capi-release/issues/31
> Document that manifest quotas updates don't apply

- app-sec-groups.html.md.erb
This makes the rule match the description "Allow http and https
traffic from ZoneA" and shows a more realistic use case.
> Change 80-443 port range to 80,443

- app-sec-groups.html.md.erb
Containers are an implementation detail. Focus on CF domain terms for high-level docs.
> Remove "containers" from ASG documentation

- container-networking.html.md.erb
- remove misleading statement about IP addresses being "accessible
outside of the Diego cell."  Replace with statement about IP
reachability between app instances.
- remove references to Calico, iovisor, etc since such integrations
with CF do not yet exist.
- attempt to standardize nomenclature: "app instances" instead of
"containers" or "app containers"
[#138950965]
@rosenhouse @rusha19
> Small fixes to CF networking docs

- docker.html.md.erb
cf CLI 6.13.0 was released in Oct 2015. Not likely anyone is on an older version and wants to use the plugin.
If anyone is still on such an older version, they'll get an error that the flag doesn't exist and probably figure out it's time to upgrade their CLI.
> remove links to docker plugin for cf CLI <v6.13.0

- isolation-segments.html.md.erb
- all users can see iso segs of their orgs, NOT iso seg of their space
- org managers, NOT just admins, can also set the default iso seg of an org, and assign/un-assign iso seg to spaces
- the default iso seg of an org must be explicitly set regardless whether org has one or more iso segs.
> Update the role permission and setting of default isolation segment

- docker.html.md.erb
We found in usability testing that people who were pushing a Docker image for
the first time were confused by the -o option in the examples. It took them a
while to work out what it meant.
First time users don't understand how the thing works and come with all sorts
of ideas about how it *might* work. For example. one participant wondered if CF
might accept a github repository name and look for a Dockerfile in it to build
an image. This is a reasonable hypothesis, consistent with previous
experience of CF from the buildpack lifecycle.
The -o option doesn't give them any clues that their hypothesis about how it
works is incorrect.
Change it to the long --docker-image argument to try to make it more explicit.
> Use --docker-image instead of -o for clarity

- isolation-segments.html.md.erb
The CC docs [1] says the request should be a PATCH, not a PUT. I've confirmed that it is a PATCH request
1. http://v3-apidocs.cloudfoundry.org/version/3.12.0/index.html#update-an-isolation-segment
> Fix update iso seg example

- isolation-segments.html.md.erb
remove unnecessary or incorrect `\` escaping. 
This time cleaned up all instances.
> Remove incorrect escapes in cURL examples of Isolation Segment doc

- notifications.html.md.erb
From description on line 76
`system-going-down` and `system-up` are made `critical`, so no users can unsubscribe from that notification , 
- system-up critical state is false in docs , should be true
> System-up critical state should be true

- isolation-segments.html.md.erb
cli does not fail when specifying an existing isolation segment.
> removed incorrect statement

- isolation-segments.html.md.erb
it's an isolation segment object to CAPI, but it's an isolation segment to end-users
> changed to be more end-user focused

- uaa-user-management.html.md.erb
For the password update instructions, it's actually the client's scope, not authorities that needs to be updated with password.write
> Password update instructions

- routing-keepalive.html.md.erb
The contents of the Gorouter Retry Behavior Table are out of order.
The correct expression should be 'If the connection is a TCP connection to the routing backend, but the app does not respond, then Gorouter retries the request three times.'
> Update Gorouter Retry Behavior Table

- custom-stack.html.md.erb
I want to update this custom stack doc for the changeover to using GrootFS as the Garden Image Plugin. This change means that rootfses must be packaged as `.tar` files.
I'm not sure in OSS CF docs if there is a convention for documenting older information as well (garden-shed will be unsupported as soon as we can make this happen). Should we have a section here for how this would work with the old garden-shed as well as Groot?
> Mention that custom stacks must use tarred rootfs

- listing-feature-flags.html.md.erb
This is a new feature flag in Cloud Foundry that allows developers to share service instances across spaces (in any orgs) that they have the SpaceDeveloper role in.
> add service_instance_sharing feature flag

- buildpacks.html.md.erb
⚠️ : Please Review before merging: I'm not sure if changing the id of the anchor is sufficient to fix all places where this is referenced. For example, I'm not sure how the TOC at the top of the page comes into existence.
This change is to avoid duplicate ids and especially prevent the 'Disabling Custom Buildpacks' TOC link jump to the 'Add a Buildpack' section.
> Please review before merging: Fix 'Add a Buildpack' HTML id

- instance-identity.html.md.erb
- Clarify minimal required configuration to enable feature
- Clarify scope of required configuration in modern BOSH manifests
- Delegate trusted system cert configuration to existing docs more completely
- Other minor edits to focus text more on CF than Diego subsystem in isolation
[#157321019]
> Edit instance identity configuration document

- securing-traffic.html.md.erb
We added the ability for operators to sanitize the X-Forwarded-Proto header, and want to document how and when operators would use it.
> Documentation for router.sanitize_forwarded_proto

- stack-auditor.html.md.erb
One would need this if they were upgrading to a version of the platform that _didn't_ have the stack you were on before.
> Change stack name

- stack-auditor.html.md.erb
The original functionality described only occurs with the `--v3` flag, which is not available in older versions of CF and not documented here. (For example, it does not work in PAS 2.4, making the functionality unavailable to PAS users entirely, as PAS 2.5 does not have cflinuxfs2.)
> Correct assumption that we can do ZDT in all circumstances

- routing-is.html.md.erb
PAS 2.7 removes the syslog_adapter instance_group, so we no longer need to allow traffic from private to shared over port 4443.
https://github.com/pivotal/pas-requests/issues/483
> remove legacy firewall port 4443

- service-mesh.html.md.erb
I delete this " The domain for routes is `*.mesh.YOUR-APPS-DOMAIN` and is not configurable" , because we provide a feature that allows users to configure the domain
> Update the limitation

- metadata.html.md.erb
Following CAPI work related to https://github.com/cloudfoundry/cloud_controller_ng/issues/1335, annotations benefit from the same prefix format including DNS subdomain.
/CC @tcdowney
> Refine Prefix section to also apply to annotations

- metadata.html.md.erb
Refine metadata alphanumeric wording with normative regexp inspired from K8S documentation at https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set
/CC @tcdowney
> Refine metadata alphanumeric format

- user-accounts-index.html.md.erb
Noticed a slight syntax error in the code that was causing the docs to show `%= vars.app_runtime_abbr %>` rather than the value of that variable.  
Turns out its due to a missing `<` character; which this PR fixes
> Fix syntax error that was preventing rendering  vars.app_runtime_abbr

- enabling-tcp-routing.html.md.erb
- metadata.html.md.erb
Hi Docs Team. We are preparing to GA cf CLI version 7. We are trying to remove references to any beta tags left behind. This is one of 3 PRs. The others should be in docs-cf-cli, docs-dev-guide.
> remove cli v7 beta references for GA

- routing-is.html.md.erb
Co-authored-by: Mark Stokan <mstokan@pivotal.io>
Co-authored-by: Gary Liu <galiu@pivotal.io>
[#172795055] Update Docs for IST firewalls with only needed ports
We did a pass on the IST firewall rules and made some updates
- limit tas-to-bosh ports to 4222, 25250, 25777
- eliminate unnecessary bosh-to-tas firewall rule
- expand tas-internal and is1-internal to tcp:any, udp:any, icmp:any
- document port 4443 - capi.blobstore.tls.port
- update Reverse Log Proxy Gateway property
- document port 8084 - Diego file server - HTTP (Small Footprint TAS)
> Validate Isolation Segment Tile Firewall Rules

- routing-is.html.md.erb
- define all ports in use
- remove is1-to-jumpbox rule
Co-authored-by: Mark Stokan <mstokan@pivotal.io>
Co-authored-by: Gary Liu <galiu@pivotal.io>
[#172795055] Update Docs for IST firewalls with only needed ports
> More documentation changes to IST firewall rules

- routing-is.html.md.erb
Co-authored-by: Gary Liu <galiu@pivotal.io>
Co-authored-by: Mark Stokan <mstokan@pivotal.io>
[#172795055] Update Docs for IST firewalls with only needed ports
> remove loggregator agent port 3457

- troubleshooting-router-error-responses.html.md.erb
to troubleshooting-router-error-responses
[#172386741](https://www.pivotaltracker.com/story/show/172386741)
Co-authored-by: Clay Kauzlaric <ckauzlaric@pivotal.io>
I made this against master, but the information is true for all versions of TAS 2.4+. All info that is version dependent is marked specifically as such.
> Add stale routes triage section 

- isolation-segments.html.md.erb
- cf cli 2.26.0 came out in 2017. 
- can prob stop warning about it in 2.10+
I think I am doing this on the 2.10, branch. If not pls lmk.
Thanks!
🐱
> remove cf cli 2.26.0 warnings

- configure-lb-healthcheck.html.md.erb
- enabling-tcp-routing.html.md.erb
- enabling_ipv6.html.md.erb
- routing-index.html.md.erb
- routing-is.html.md.erb
- routing-keepalive.html.md.erb
- securing-traffic.html.md.erb
- supporting-websockets.html.md.erb
- troubleshooting-router-error-responses.html.md.erb
- troubleshooting_slow_requests.html.md.erb
- troubleshooting_tcp_routing.html.md.erb
- zipkin_tracing.html.md.erb
Replaces:
- Routing
[#174581818](https://www.pivotaltracker.com/story/show/174581818)
This change should also be backported all the way back to TAS `2.7` 
- https://github.com/cloudfoundry/docs-dev-guide/pull/410
- https://github.com/cloudfoundry/docs-cf-admin/pull/189
- https://github.com/cloudfoundry/docs-cloudfoundry-concepts/pull/146
- https://github.com/pivotal-cf/docs-operating-pas/pull/38
- https://github.com/pivotal-cf/docs-ops-manager/pull/93
- https://github.com/pivotal-cf/docs-pcf-security/pull/116
>  Update owner: CF for VMs Networking

- enabling-tcp-routing.html.md.erb
Merges content of:
- docs-cf-admin/enabling-tcp-routing
- docs-operating-pas/tcp-routing-ert-config
into → docs-cf-admin/enabling-tcp-routing
Tracker: [#174580463](https://www.pivotaltracker.com/story/show/174580463)
Please backport this change to TAS `2.7`.
Related PRs:
- cloudfoundry/docs-cf-admin#192
- pivotal-cf/docs-operating-pas#39
- pivotal-cf/docs-partials#28
> Consolidate TCP Routing pages

- supporting-websockets.html.md.erb
WebSockets are not supported for routes bound to route services
See https://github.com/cloudfoundry/gorouter/commit/1bf9a13a98ef2230760b572186d52acc0fad9bad
/CC @shalako
> WebSockets are not supported with route services

- troubleshooting-router-error-responses.html.md.erb
- Makes `ha_proxy.skip_cert_verify` (Skip SSL Certificate Verification)
unconfigurable and defaulted to `false`
- Removes the form from the tile UI
- Adds migration to prevent upgrading when this feature is configured
`true`
- Removes all documentation referencing to this setting
- Updates Ops Man documentation for case when users want to provide
their own self-signed certificate
[#174811172](https://www.pivotaltracker.com/story/show/174811172)
Co-authored-by: Josh Russett <jrussett@vmware.com>
Co-authored-by: Ryan Hall <hallr@vmware.com>
None
- pivotal-cf/p-runtime#1826
- pivotal-cf/p-isolation-segment#503
- pivotal-cf/docs-partials#31
- cloudfoundry/docs-cf-admin#194
- pivotal-cf/docs-operating-pas#41
- pivotal-cf/docs-pivotalcf-console#16
> Remove "Skip SSL Certificate Verification"

- docker.html.md.erb
- troubleshooting-router-error-responses.html.md.erb
tl;dr: The information contained on that page was represented elsewhere and the page no longer needs to exist.
- the home for the majority of this content is in:
- `docs-cloudfoundry-concepts/cf-routing-architecture.html`
- `docs-cf-admin/troubleshooting-router-error-responses.html`
- Removes the following file and all links to file: `docs-cloudfoundry-concepts/architecture/router.html(.md.erb)`
- change link destinations to a more appropriate page
- usually `docs-cloudfoundry-concepts/cf-routing-architecture.html`
- reorganize the flow of `docs-cloudfoundry-concepts/cf-routing-architecture.html`
PivotalTracker: [#174579096](https://www.pivotaltracker.com/story/show/174579096)
Please backport these changes to TAS 2.7.
- cloudfoundry/docs-cloudfoundry-concepts/pull/148
- …
> Remove redundant gorouter arch doc

- enabling-tcp-routing.html.md.erb
* Provide guidance on what are (and are not) safe port ranges to use as reservable_ports
* Update example to use range that is safer by default
* Update example to show comma-separated port ranges
* Reference modify-ports section in earlier docs about choosing portranges
Related:
https://github.com/cloudfoundry/routing-release/issues/184
> Update TCP routing docs for reservable ports

- troubleshooting-router-error-responses.html.md.erb
Making sure this doc is in sync with [this doc](https://docs.pivotal.io/application-service/2-11/concepts/http-routing.html#retry)
> Update gorouter for read: connection reset by peer

- routing-keepalive.html.md.erb
- troubleshooting-router-error-responses.html.md.erb
Hi folks, 
When Gorouter back end keep-alive connections is enabled, users are exposed to a potential race condition if their application keep-alive idle timeouts are not correctly configured. This PR updates the docs to inform users about this.
The Gorouter backend idle timeout value of 90 seconds comes from [this](https://github.com/cloudfoundry/gorouter/blob/main/proxy/proxy.go#L113) hardcoded value.
Supporting information about why it's important for _senders_ to close connections before _receivers_ do:
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html
> To ensure that the load balancer is responsible for closing the connections to your instance, **make sure that the value you set for the HTTP keep-alive time is greater than the idle timeout …
> Update Gorouter Back End Keep-Alive Connections Docs with Caveat about Potential Race Condition

- routing-keepalive.html.md.erb
Emphasize the importance of setting app container keep-alive idle timeout to be greater than 90 seconds. We have been spending quite some time, with multiple support cases, and this turned out to be the reason/solution. Hope the emphasis will save others time.
> Emphasize more on the backend idle-timeout for app containers

- troubleshooting_slow_requests.html.md.erb
Explains what the difference between response_time + gorouter_time
is, and provides some more pointers when troubleshooting to make use
of the additional latency information.
> Add gorouter_time info to the troubleshooting slow requests doc

- routing-index.html.md.erb
- supporting-http2.html.md.erb
Related PRs:
- Nav: https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/112
- Dev Guide: https://github.com/cloudfoundry/docs-dev-guide/pull/437
Root Issue: cloudfoundry/routing-release#200
> Add operator docs for HTTP/2 support

- configure-lb-healthcheck.html.md.erb
If the health check ports are not able to be configured then the existing documentation reads strangely.
Move the reference to modifying ports to within the same conditional as the text it is referring to.
> Distribution may not support customising the router status port

- supporting-http2.html.md.erb
- supporting-websockets.html.md.erb
Related issue: https://github.com/cloudfoundry/routing-release/issues/230
[cloudfoundry/routing-release#200]
> Add docs for HTTP/2 WebSockets

- troubleshooting-router-error-responses.html.md.erb
`<x>` and `<y>` are not rendered within a html code element, 
therefore this commit introduces spaces.
Fixes formatting error introduced with 5dc50dd0521cdca91d287a44c59f691011165c93
Furthermore, adds a missing comma.
Signed-off-by: Jürgen Walter <juergen.walter@sap.com>
> Fix HostnameMismatch troubleshooting formatting

- routing-is.html.md.erb
Recently [the default for Log Cache ingress was changed in cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases/tag/v18.0.0). Log Cache had been using the Reverse Log Proxy by default but now defaults to using syslog ingress.
This means that Diego Cells need to be able to initiate connections to the Log Cache Syslog Server. This PR updates the *Routing for Isolation Segments* docs to include port 6067 which is the [default port that Log Cache Syslog Server listens on](https://github.com/cloudfoundry/log-cache-release/blob/v2.11.6/jobs/log-cache-syslog-server/spec#L31-L33).
I've also added port 4224 which may need to be open for secure NATS communication, and removed a vendor-specific reference.
Please let me know if you would like us to issue separate PRs for earlier docs …
> Document log cache syslog server port

- troubleshooting-router-error-responses.html.md.erb
We noticed that the documentation for Gorouter retry logic is no longer up-to-date.
The change was implemented in [this pull request](https://github.com/cloudfoundry/gorouter/pull/284) and is also documented very well there.
> Update Gorouter retry behaviour for idempotent requests

- listing-feature-flags.html.md.erb
Change description of the feature flag `env_var_visibility` and `space_developer_env_var_visibility` to match the CC's behaviour.
> Fix feature-flag description

- configuring-delayed-job-priorities.html.md.erb
- delayed-jobs-index.html.md.erb
- index.html.md.erb
Documentation for configuring delayed job priorities.
Related ccng/capi PRs:
- https://github.com/cloudfoundry/cloud_controller_ng/pull/2693
- https://github.com/cloudfoundry/capi-release/pull/227
PR for navigation bar: https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/118
> Add documentation for configuring delayed job priorities

- using-cpu-entitlement-plugin.html.md.erb
This PR is part of a group of 3 PRs.
* https://github.com/pivotal-cf/docs-partials/pull/87
*  Adds partials about cpu-entitlement.
*  Adds sidenav entries for the TAS specific cpu entitlement docs.
* https://github.com/cloudfoundry/docs-cf-admin/pull/221 👈  This PR
* Updates the open source CF cpu entitlement doc to use the partials. 
* https://github.com/pivotal-cf/docs-operating-pas/pull/106
* Creates the TAS specific cpu entitlement doc.
* This doc uses the partials from the first PR.
* And it is linked to in the sidenav by the first PR.
✨ Please let me know if you have any questions or if I need to fix anything!
> move cpu entitlement docs to use partials

- metadata.html.md.erb
This feature has been present since CAPI 1.97.0 and we thought it deserved to be better known.
@anita-flegg Please let me know if you'd like us to backport this to earlier versions of the docs.
> Document adding custom log and metric tags

- metadata.html.md.erb
This feature has been present since CAPI 1.97.0:
(cherry picked from commit d7370b9cc197d2be3ecaf1c466c2775b4f31dde3)
> Document adding custom log and metric tags - 15.4

- metadata.html.md.erb
This feature has been present since CAPI 1.97.0:
(cherry picked from commit d7370b9cc197d2be3ecaf1c466c2775b4f31dde3)
> Document adding custom log and metric tags - 16.24

- metadata.html.md.erb
This feature has been present since CAPI 1.97.0:
(cherry picked from commit d7370b9cc197d2be3ecaf1c466c2775b4f31dde3)
> Document adding custom log and metric tags - 19.0

- metadata.html.md.erb
This feature has been present since CAPI 1.97.0:
(cherry picked from commit d7370b9cc197d2be3ecaf1c466c2775b4f31dde3)
> Document adding custom log and metric tags - 22.0

- routing-is.html.md.erb
Operators should ensure connections to syslog endpoints (ports may vary) are allowed from both diego cells and routers within an isolation segment.
> Include note to consider syslog drains

- routing-is.html.md.erb
While System Metrics Agent port's default was 9100, we saw that it was being overridden to 53035 in every install we know of. The system-metrics-agent default has been updated to 53035 to reflect this as well.
> Update System Metrics Agent port

- quota-plans.html.md.erb
There probably was a copy typo from set-org-quota and the argument was still set as ORG instead of SPACE.
> fix: set-space-quota to use SPACE argument

- quota-plans.html.md.erb
The Org quota plan attributes in the cloudfoundry documentation were not in line with the organization quota object from the [v3-apidocs](https://v3-apidocs.cloudfoundry.org/version/3.152.0/#organization-quotas). Updating the documentation to actual status.
>  Adjust org quota plan attributes

- _lock_buildpack.html.md.erb
This PR updates CAPI v2 docs links from `apidocs.cloudfoundry.org` to `v2-apidocs.cloudfoundry.org`.
The goal is to signal that v3 is the primary API, also a necessary step in eventually sunsetting v2.
~~The infrastructure hosting the app serving docs at apidocs.cloudfoundry.org is expected to go down imminently, so this change is needed to avoid dead links.~~
`apidocs.cloudfoundry.org` has been converted to a redirect to `v3-apidocs.cloudfoundry.org`, so this change is needed to avoid incorrect links
See capi-release PRs [#440](https://github.com/cloudfoundry/capi-release/pull/440) and [#441](https://github.com/cloudfoundry/capi-release/pull/441)
> Update CAPI v2 docs links to new subdomain

- supporting-websockets.html.md.erb
[WebSocket Support for Apps with Route-Services](https://github.com/cloudfoundry/routing-release/pull/474)
HTTP2 is also supported in the meantime
> Web socket support was implemented
